var dictionary = [
        { term: "3D printing", translation: "Percetakan 3D" },
        { term: "4K resolution", translation: "Resolusi 4K" },
        { term: "Access control", translation: "Kontrol akses" },
        { term: "Adaptive software", translation: "Perangkat lunak adaptif" },
        { term: "Adware", translation: "Perangkat lunak iklan" },
        { term: "Algorithm", translation: "Algoritma" },
        { term: "Algorithmic trading", translation: "Perdagangan algoritmik" },
        { term: "Ambient computing", translation: "Komputasi ambiens" },
        { term: "Analog", translation: "Analog" },
        { term: "Animation", translation: "Animasi" },
        { term: "Anonymizer", translation: "Anonimiser" },
        { term: "Antivirus", translation: "Antivirus" },
        { term: "API (Application Programming Interface)", translation: "API (Antarmuka Pemrograman Aplikasi)" },
        { term: "App", translation: "Aplikasi" },
        { term: "Application", translation: "Aplikasi" },
        { term: "Archiving", translation: "Pengarsipan" },
        { term: "ARP (Address Resolution Protocol)", translation: "ARP (Protokol Resolusi Alamat)" },
        { term: "Artificial Intelligence (AI)", translation: "Kecerdasan Buatan (AI)" },
        { term: "Augmented Reality (AR)", translation: "Realitas Tertambah (AR)" },
        { term: "Authentication", translation: "Otentikasi" },
        { term: "Authentication token", translation: "Token otentikasi" },
        { term: "Autoresponder", translation: "Autoresponder" },
        { term: "Avatar", translation: "Avatar" },
        { term: "Backend", translation: "Backend" },
        { term: "Bandwidth", translation: "Lebar pita" },
        { term: "Bandwidth throttling", translation: "Penyesuaian lebar pita" },
        { term: "Base64", translation: "Basis64" },
        { term: "Benchmark", translation: "Tolak ukur" },
        { term: "Big Data", translation: "Data besar" },
        { term: "Binary", translation: "Biner" },
        { term: "Binary tree", translation: "Pohon biner" },
        { term: "BIOS", translation: "BIOS" },
        { term: "BIOS update", translation: "Pembaruan BIOS" },
        { term: "Bit", translation: "Bit" },
        { term: "Bit rate", translation: "Laju bit" },
        { term: "Bitmap", translation: "Bitmap" },
        { term: "Black hat", translation: "Topi hitam" },
        { term: "Blockchain", translation: "Rantai blok" },
        { term: "Bluetooth", translation: "Bluetooth" },
        { term: "Bluetooth LE (Low Energy)", translation: "Bluetooth LE (Energi Rendah)" },
        { term: "Bookmark", translation: "Tandai" },
        { term: "Boolean", translation: "Boolean" },
        { term: "Bot", translation: "Bot" },
        { term: "Bootstrap", translation: "Bootstrap" },
        { term: "Brute force", translation: "Paksaan kasar" },
        { term: "Buffer", translation: "Buffer" },
        { term: "Buffer overflow", translation: "Tumpah buffer" },
        { term: "Bug", translation: "Bug" },
        { term: "Buggy", translation: "Kecelakaan" },
        { term: "Build automation", translation: "Automatisasi pembangunan" },
        { term: "Burn", translation: "Bakar" },
        { term: "Bus", translation: "Bus" },
        { term: "Byte", translation: "Byte" },
        { term: "Cache", translation: "Cache" },
        { term: "Call stack", translation: "Tumpukan panggilan" },
        { term: "Camera", translation: "Kamera" },
        { term: "Capture", translation: "Penangkapan" },
        { term: "Case sensitive", translation: "Peka huruf besar-kecil" },
        { term: "CD (Compact Disc)", translation: "CD (Compact Disc)" },
        { term: "CD-ROM", translation: "CD-ROM" },
        { term: "Cellular network", translation: "Jaringan seluler" },
        { term: "Chatbot", translation: "Chatbot" },
        { term: "Checksum", translation: "Checksum" },
        { term: "Chrome", translation: "Chrome" },
        { term: "Circuit", translation: "Sirkuit" },
        { term: "Client", translation: "Klien" },
        { term: "Cloud computing", translation: "Komputasi awan" },
        { term: "Cluster", translation: "Klaster" },
        { term: "Codec", translation: "Codec" },
        { term: "Command", translation: "Perintah" },
        { term: "Command-line interface (CLI)", translation: "Antarmuka baris perintah (CLI)" },
        { term: "Compiler", translation: "Compiler" },
        { term: "Computer", translation: "Komputer" },
        { term: "Computer-aided design (CAD)", translation: "Desain berbantu komputer (CAD)" },
        { term: "Computer virus", translation: "Virus komputer" },
        { term: "Concatenate", translation: "Konkatenasi" },
        { term: "Cookie", translation: "Cookie" },
        { term: "Copy", translation: "Salin" },
        { term: "Cracker", translation: "Pengganggu" },
        { term: "Crash", translation: "Crash" },
        { term: "Creative Commons", translation: "Creative Commons" },
        { term: "Credential", translation: "Kredensial" },
        { term: "Crumb trail", translation: "Jejak remah" },
        { term: "Cryptocurrency", translation: "Kriptokurensi" },
        { term: "CSS (Cascading Style Sheets)", translation: "CSS (Cascading Style Sheets)" },
        { term: "Cursor", translation: "Kursor" },
        { term: "Cyberattack", translation: "Serangan siber" },
        { term: "Cyberbullying", translation: "Penggertakan siber" },
        { term: "Cybercrime", translation: "Kejahatan siber" },
        { term: "Cybersecurity", translation: "Keamanan siber" },
        { term: "Cyberspace", translation: "Siber" },
        { term: "Daemon", translation: "Daemon" },
        { term: "Data", translation: "Data" },
        { term: "Data center", translation: "Pusat data" },
        { term: "Data compression", translation: "Kompresi data" },
        { term: "Data mining", translation: "Penggalian data" },
        { term: "Data recovery", translation: "Pemulihan data" },
        { term: "Data science", translation: "Ilmu data" },
        { term: "Data structure", translation: "Struktur data" },
        { term: "Data type", translation: "Jenis data" },
        { term: "Database", translation: "Basis data" },
        { term: "DBMS (Database Management System)", translation: "DBMS (Sistem Manajemen Basis Data)" },
        { term: "Debug", translation: "Debug" },
        { term: "Debugger", translation: "Debugger" },
        { term: "Decryption", translation: "Dekripsi" },
        { term: "Deep learning", translation: "Pembelajaran mendalam" },
        { term: "Default", translation: "Default" },
        { term: "Defragmentation", translation: "Defragmentasi" },
        { term: "Delete", translation: "Hapus" },
        { term: "Denial of Service (DoS)", translation: "Penolakan Layanan (DoS)" },
        { term: "Desktop", translation: "Desktop" },
        { term: "Desktop publishing", translation: "Penerbitan desktop" },
        { term: "Developer", translation: "Pengembang" },
        { term: "DHCP (Dynamic Host Configuration Protocol)", translation: "DHCP (Protokol Konfigurasi Host Dinamis)" },
        { term: "Digital", translation: "Digital" },
        { term: "Digital divide", translation: "Pembagian digital" },
        { term: "Digital footprint", translation: "Jejak digital" },
        { term: "Digital signature", translation: "Tanda tangan digital" },
        { term: "Directory", translation: "Direktori" },
        { term: "Disaster recovery", translation: "Pemulihan bencana" },
        { term: "Disk", translation: "Disk" },
        { term: "Disk image", translation: "Gambar disk" },
        { term: "Disk partition", translation: "Partisi disk" },
        { term: "Display", translation: "Tampilan" },
        { term: "Disruptive technology", translation: "Teknologi yang mengganggu" },
        { term: "Distributed computing", translation: "Komputasi terdistribusi" },
        { term: "Dithering", translation: "Dithering" },
        { term: "Domain", translation: "Domain" },
        { term: "Domain name", translation: "Nama domain" },
        { term: "Download", translation: "Unduh" },
        { term: "DRAM (Dynamic Random Access Memory)", translation: "DRAM (Memori Akses Acak Dinamis)" },
        { term: "Driver", translation: "Driver" },
        { term: "Drop-down list", translation: "Daftar drop-down" },
        { term: "DSL (Digital Subscriber Line)", translation: "DSL (Digital Subscriber Line)" },
        { term: "DVD (Digital Versatile Disc)", translation: "DVD (Digital Versatile Disc)" },
        { term: "Dynamic", translation: "Dinamis" },
        { term: "E-commerce", translation: "E-commerce" },
        { term: "Ebook", translation: "Ebook" },
        { term: "ECC (Error Correcting Code)", translation: "ECC (Kode Koreksi Kesalahan)" },
        { term: "Edge computing", translation: "Komputasi tepi" },
        { term: "Editor", translation: "Editor" },
        { term: "EDR (Endpoint Detection and Response)", translation: "EDR (Deteksi dan Respons Ujung)" },
        { term: "EFS (Encrypting File System)", translation: "EFS (Sistem Berkas Enkripsi)" },
        { term: "Email", translation: "Email" },
        { term: "Emoticon", translation: "Emotikon" },
        { term: "Encryption", translation: "Enkripsi" },
        { term: "End-user", translation: "Pengguna akhir" },
        { term: "Endpoint", translation: "Ujung" },
        { term: "Energy efficiency", translation: "Efisiensi energi" },
        { term: "Energy star", translation: "Bintang energi" },
        { term: "Engineering", translation: "Teknik" },
        { term: "Enrollment", translation: "Pendaftaran" },
        { term: "Enterprise", translation: "Perusahaan" },
        { term: "Enterprise resource planning (ERP)", translation: "Perencanaan sumber daya perusahaan (ERP)" },
        { term: "Entity", translation: "Entitas" },
        { term: "Environment", translation: "Lingkungan" },
        { term: "EPROM (Erasable Programmable Read-Only Memory)", translation: "EPROM (Memori Baca-Tulis Terprogram yang Dapat Dihapus)" },
        { term: "Error", translation: "Kesalahan" },
        { term: "Ethernet", translation: "Ethernet" },
        { term: "Evil twin", translation: "Kembar jahat" },
        { term: "Executable file", translation: "Berkas yang dapat dieksekusi" },
        { term: "Exit", translation: "Keluar" },
        { term: "Exploit", translation: "Eksploitasi" },
        { term: "Extension", translation: "Ekstensi" },
        { term: "Extranet", translation: "Extranet" },
        { term: "FAT (File Allocation Table)", translation: "FAT (Tabel Penugasan Berkas)" },
        { term: "Fault tolerance", translation: "Toleransi kesalahan" },
        { term: "Favicon", translation: "Favicon" },
        { term: "Fiber optic", translation: "Serat optik" },
        { term: "File", translation: "Berkas" },
        { term: "File format", translation: "Format berkas" },
        { term: "File server", translation: "Server berkas" },
        { term: "Filename", translation: "Nama berkas" },
        { term: "Firewall", translation: "Firewall" },
        { term: "Firmware", translation: "Firmware" },
        { term: "Flash drive", translation: "Flash drive" },
        { term: "Flash memory", translation: "Memori flash" },
        { term: "Floppy disk", translation: "Disket" },
        { term: "Flowchart", translation: "Diagram alir" },
        { term: "Folder", translation: "Folder" },
        { term: "Font", translation: "Font" },
        { term: "Footprint", translation: "Jejak" },
        { term: "Form", translation: "Formulir" },
        { term: "Format", translation: "Format" },
        { term: "Formula", translation: "Formula" },
        { term: "Forum", translation: "Forum" },
        { term: "Framework", translation: "Kerangka kerja" },
        { term: "Freeware", translation: "Freeware" },
        { term: "FTP (File Transfer Protocol)", translation: "FTP (Protokol Transfer Berkas)" },
        { term: "Function", translation: "Fungsi" },
        { term: "Gaming", translation: "Bermain game" },
        { term: "Gateway", translation: "Gerbang" },
        { term: "GIF (Graphics Interchange Format)", translation: "GIF (Format Pertukaran Grafis)" },
        { term: "Gigabyte", translation: "Gigabyte" },
        { term: "GIS (Geographic Information System)", translation: "GIS (Sistem Informasi Geografis)" },
        { term: "GitHub", translation: "GitHub" },
        { term: "GPS (Global Positioning System)", translation: "GPS (Sistem Pemosisian Global)" },
        { term: "GPU (Graphics Processing Unit)", translation: "GPU (Unit Pemrosesan Grafis)" },
        { term: "Grammar checker", translation: "Pemeriksa tata bahasa" },
        { term: "Graphics", translation: "Grafis" },
        { term: "Graphical user interface (GUI)", translation: "Antarmuka pengguna grafis (GUI)" },
        { term: "Grid computing", translation: "Komputasi grid" },
        { term: "Groupware", translation: "Groupware" },
        { term: "GUI (Graphical User Interface)", translation: "GUI (Antarmuka Pengguna Grafis)" },
        { term: "Hacker", translation: "Peretas" },
        { term: "Hard drive", translation: "Hard drive" },
        { term: "Hardware", translation: "Perangkat keras" },
        { term: "Hash", translation: "Hash" },
        { term: "HDMI (High-translation Multimedia Interface)", translation: "HDMI (Antarmuka Multimedia Definisi Tinggi)" },
        { term: "Header", translation: "Header" },
        { term: "Heap", translation: "Tumpukan" },
        { term: "Helpdesk", translation: "Helpdesk" },
        { term: "Hibernate", translation: "Hibernasi" },
        { term: "Home page", translation: "Halaman utama" },
        { term: "Host", translation: "Host" },
        { term: "Hotspot", translation: "Hotspot" },
        { term: "HTML (Hypertext Markup Language)", translation: "HTML (Bahasa Pemformatan Hiperteks)" },
        { term: "HTTP (Hypertext Transfer Protocol)", translation: "HTTP (Protokol Transfer Hiperteks)" },
        { term: "HTTPS (Hypertext Transfer Protocol Secure)", translation: "HTTPS (Protokol Transfer Hiperteks Aman)" },
        { term: "Hub", translation: "Hub" },
        { term: "Hybrid", translation: "Hibrida" },
        { term: "Hyperlink", translation: "Hyperlink" },
        { term: "Hypertext", translation: "Hiperteks" },
        { term: "Icon", translation: "Ikon" },
        { term: "IDE (Integrated Development Environment)", translation: "IDE ( Lingkungan Pengembangan Terpadu)" },
        { term: "Identity theft", translation: "Pencurian identitas" },
        { term: "Image", translation: "Gambar" },
        { term: "IMAP (Internet Message Access Protocol)", translation: "IMAP (Protokol Akses Pesan Internet)" },
        { term: "Impact printer", translation: "Printer dampak" },
        { term: "Implementation", translation: "Implementasi" },
        { term: "Input", translation: "Input" },
        { term: "Input device", translation: "Perangkat masukan" },
        { term: "Installation", translation: "Pemasangan" },
        { term: "Instant messaging", translation: "Pesan instan" },
        { term: "Integer", translation: "Integer" },
        { term: "Integrated circuit", translation: "Sirkuit terpadu" },
        { term: "Integration", translation: "Integrasi" },
        { term: "Interface", translation: "Antarmuka" },
        { term: "Internet", translation: "Internet" },
        { term: "Internet Explorer", translation: "Internet Explorer" },
        { term: "Internet of Things (IoT)", translation: "Internet of Things (IoT)" },
        { term: "Internet service provider (ISP)", translation: "Penyedia layanan internet (ISP)" },
        { term: "Interoperability", translation: "Interoperabilitas" },
        { term: "Interpreter", translation: "Penerjemah" },
        { term: "Intranet", translation: "Intranet" },
        { term: "IP address (Internet Protocol address)", translation: "Alamat IP (Alamat Protokol Internet)" },
        { term: "IP telephony", translation: "Telepon IP" },
        { term: "ISDN (Integrated Services Digital Network)", translation: "ISDN (Jaringan Digital Layanan Terpadu)" },
        { term: "ISP (Internet Service Provider)", translation: "ISP (Penyedia Layanan Internet)" },
        { term: "Iterate", translation: "Iterasi" },
        { term: "IT (Information Technology)", translation: "IT (Teknologi Informasi)" },
        { term: "Jabber", translation: "Jabber" },
        { term: "Java", translation: "Java" },
        { term: "JavaScript", translation: "JavaScript" },
        { term: "Joystick", translation: "Joystick" },
        { term: "JPEG (Joint Photographic Experts Group)", translation: "JPEG (Kelompok Ahli Fotografi Bersama)" },
        { term: "JSON (JavaScript Object Notation)", translation: "JSON (Notasi Objek JavaScript)" },
        { term: "JSP (JavaServer Pages)", translation: "JSP (JavaServer Pages)" },
        { term: "Kbps (Kilobits per second)", translation: "Kbps (Kilobit per detik)" },
        { term: "Keyboard", translation: "Keyboard" },
        { term: "Keylogger", translation: "Perekam ketikan" },
        { term: "Keyword", translation: "Kata kunci" },
        { term: "Kiosk", translation: "Kios" },
        { term: "LAN (Local Area Network)", translation: "LAN (Jaringan Area Lokal)" },
        { term: "Latency", translation: "Latensi" },
        { term: "LCD (Liquid Crystal Display)", translation: "LCD (Tampilan Kristal Cair)" },
        { term: "LED (Light Emitting Diode)", translation: "LED (Dioda Penyala)" },
        { term: "Library", translation: "Perpustakaan" },
        { term: "License", translation: "Lisensi" },
        { term: "Lifecycle", translation: "Siklus hidup" },
        { term: "Lightning port", translation: "Port lightning" },
        { term: "Link", translation: "Tautan" },
        { term: "Linux", translation: "Linux" },
        { term: "List", translation: "Daftar" },
        { term: "Localhost", translation: "Localhost" },
        { term: "Lockdown", translation: "Pembatasan" },
        { term: "Logic", translation: "Logika" },
        { term: "Login", translation: "Masuk" },
        { term: "Logout", translation: "Keluar" },
        { term: "Loop", translation: "Loop" },
        { term: "Lossless compression", translation: "Kompresi tanpa kehilangan" },
        { term: "Lossy compression", translation: "Kompresi berkurang" },
        { term: "Machine learning", translation: "Pembelajaran mesin" },
        { term: "Macro", translation: "Makro" },
        { term: "Mainframe", translation: "Mainframe" },
        { term: "Malware", translation: "Malware" },
        { term: "Mapper", translation: "Pemeta" },
        { term: "Markup", translation: "Markup" },
        { term: "Mashup", translation: "Mashup" },
        { term: "Megabyte", translation: "Megabyte" },
        { term: "Memory", translation: "Memori" },
        { term: "Menu", translation: "Menu" },
        { term: "Metadata", translation: "Metadata" },
        { term: "Metered connection", translation: "Koneksi yang dihitung" },
        { term: "Microblog", translation: "Microblog" },
        { term: "Microcontroller", translation: "Microcontroller" },
        { term: "Microphone", translation: "Mikrofon" },
        { term: "Middleware", translation: "Middleware" },
        { term: "Migration", translation: "Migrasi" },
        { term: "Millisecond", translation: "Milidetik" },
        { term: "Minicomputer", translation: "Minikomputer" },
        { term: "Mirror", translation: "Cermin" },
        { term: "MIT (Massachusetts Institute of Technology)", translation: "MIT (Institut Teknologi Massachusetts)" },
        { term: "Mobile", translation: "Seluler" },
        { term: "Modem", translation: "Modem" },
        { term: "Monitor", translation: "Monitor" },
        { term: "Motherboard", translation: "Motherboard" },
        { term: "Mouse", translation: "Mouse" },
        { term: "MP3", translation: "MP3" },
        { term: "MP4", translation: "MP4" },
        { term: "Multimedia", translation: "Multimedia" },
        { term: "Multitasking", translation: "Multitasking" },
        { term: "Nanotechnology", translation: "Nanoteknologi" },
        { term: "NAS (Network Attached Storage)", translation: "NAS (Penyimpanan Terpasang Jaringan)" },
        { term: "Navigation", translation: "Navigasi" },
        { term: "Netiquette", translation: "Netiket" },
        { term: "Network", translation: "Jaringan" },
        { term: "Network adapter", translation: "Adaptor jaringan" },
        { term: "Network card", translation: "Kartu jaringan" },
        { term: "Network drive", translation: "Drive jaringan" },
        { term: "Network interface card (NIC)", translation: "Kartu antarmuka jaringan (NIC)" },
        { term: "Network security", translation: "Keamanan jaringan" },
        { term: "Network topology", translation: "Topologi jaringan" },
        { term: "Newsgroup", translation: "Kelompok berita" },
        { term: "Node", translation: "Node" },
        { term: "Node.js", translation: "Node.js" },
        { term: "Noise-canceling", translation: "Pembatal kebisingan" },
        { term: "Nonvolatile memory", translation: "Memori non-volatil" },
        { term: "Notebook", translation: "Notebook" },
        { term: "Notification", translation: "Pemberitahuan" },
        { term: "Null", translation: "Nol" },
        { term: "Numeric", translation: "Numerik" },
        { term: "OCR (Optical Character Recognition)", translation: "OCR (Pengenalan Karakter Optik)" },
        { term: "OEM (Original Equipment Manufacturer)", translation: "OEM (Pabrikan Peralatan Asli)" },
        { term: "Offline", translation: "Luar jaringan" },
        { term: "Online", translation: "Daring" },
        { term: "Open source", translation: "Sumber terbuka" },
        { term: "Operating system (OS)", translation: "Sistem operasi (OS)" },
        { term: "Optical character recognition (OCR)", translation: "Pengenalan karakter optik (OCR)" },
        { term: "Optimize", translation: "Optimalkan" },
        { term: "Oracle", translation: "Oracle" },
        { term: "OS (Operating System)", translation: "OS (Sistem Operasi)" },
        { term: "Output", translation: "Output" },
        { term: "Output device", translation: "Perangkat keluaran" },
        { term: "Packet", translation: "Paket" },
        { term: "Packet sniffing", translation: "Pengendus paket" },
        { term: "Page", translation: "Halaman" },
        { term: "Page layout", translation: "Tata letak halaman" },
        { term: "Page rank", translation: "Peringkat halaman" },
        { term: "Parallel computing", translation: "Komputasi paralel" },
        { term: "Parameter", translation: "Parameter" },
        { term: "Parent directory", translation: "Direktori induk" },
        { term: "Partition", translation: "Partisi" },
        { term: "Password", translation: "Kata sandi" },
        { term: "Paste", translation: "Tempel" },
        { term: "Patch", translation: "Perbaikan" },
        { term: "Path", translation: "Jalur" },
        { term: "Pattern", translation: "Pola" },
        { term: "Payload", translation: "Muatan" },
        { term: "PDF (Portable Document Format)", translation: "PDF (Format Dokumen Portabel)" },
        { term: "Pen drive", translation: "Pen drive" },
        { term: "Peripheral", translation: "Peripheral" },
        { term: "Perl", translation: "Perl" },
        { term: "Personal computer (PC)", translation: "Komputer pribadi (PC)" },
        { term: "Personal data assistant (PDA)", translation: "Asisten data pribadi (PDA)" },
        { term: "Pharming", translation: "Pharming" },
        { term: "Phishing", translation: "Phishing" },
        { term: "PHP (Hypertext Preprocessor)", translation: "PHP (Hypertext Preprocessor)" },
        { term: "Piconet", translation: "Piconet" },
        { term: "Ping", translation: "Ping" },
        { term: "Pixel", translation: "Pixel" },
        { term: "Plagiarism", translation: "Plagiarisme" },
        { term: "Platform", translation: "Platform" },
        { term: "Plug-in", translation: "Plug-in" },
        { term: "PNG (Portable Network Graphics)", translation: "PNG (Grafik Jaringan Portabel)" },
        { term: "Podcast", translation: "Podcast" },
        { term: "Poisoning", translation: "Pencemaran" },
        { term: "Popup", translation: "Popup" },
        { term: "Portal", translation: "Portal" },
        { term: "Port scanner", translation: "Pemindai port" },
        { term: "Post", translation: "Pos" },
        { term: "Power management", translation: "Manajemen daya" },
        { term: "PPP (Point-to-Point Protocol)", translation: "PPP (Protokol Titik ke Titik)" },
        { term: "Predictive text", translation: "Teks prediktif" },
        { term: "Presentation", translation: "Presentasi" },
        { term: "Printer", translation: "Printer" },
        { term: "Private key", translation: "Kunci pribadi" },
        { term: "Processor", translation: "Prosesor" },
        { term: "Productivity software", translation: "Perangkat lunak produktivitas" },
        { term: "Program", translation: "Program" },
        { term: "Programming", translation: "Pemrograman" },
        { term: "Programming language", translation: "Bahasa pemrograman" },
        { term: "Protocol", translation: "Protokol" },
        { term: "Proxy server", translation: "Server proxy" },
        { term: "Pulse code modulation (PCM)", translation: "Modulasi kode pulsa (PCM)" },
        { term: "Python", translation: "Python" },
        { term: "QWERTY keyboard", translation: "Papan ketik QWERTY" },
        { term: "RAID (Redundant Array of Independent Disks)", translation: "RAID (Kumpulan Disk Independen yang Redundan)" },
        { term: "RAM (Random Access Memory)", translation: "RAM (Memori Akses Acak)" },
        { term: "Raster graphics", translation: "Grafis raster" },
        { term: "RDBMS (Relational Database Management System)", translation: "RDBMS (Sistem Manajemen Basis Data Relasional)" },
        { term: "Read-only memory (ROM)", translation: "Memori hanya baca (ROM)" },
        { term: "Reboot", translation: "Reboot" },
        { term: "Recovery", translation: "Pemulihan" },
        { term: "Redundancy", translation: "Redundansi" },
        { term: "Redundant", translation: "Redundan" },
        { term: "Refactoring", translation: "Refaktoring" },
        { term: "Referral", translation: "Rujukan" },
        { term: "Refurbished", translation: "Refurbished" },
        { term: "Regression testing", translation: "Pengujian regresi" },
        { term: "Registry", translation: "Registri" },
        { term: "Relational database", translation: "Basis data relasional" },
        { term: "Reliability", translation: "Keandalan" },
        { term: "Rendering", translation: "Rendering" },
        { term: "Repair", translation: "Perbaikan" },
        { term: "Repository", translation: "Repositori" },
        { term: "Request", translation: "Permintaan" },
        { term: "Reset", translation: "Reset" },
        { term: "Resolution", translation: "Resolusi" },
        { term: "Response", translation: "Tanggapan" },
        { term: "Responsive design", translation: "Desain responsif" },
        { term: "Restore", translation: "Pulihkan" },
        { term: "RFID (Radio-Frequency Identification)", translation: "RFID (Identifikasi Frekuensi Radio)" },
        { term: "RIP (Raster Image Processor)", translation: "RIP (Pemroses Gambar Raster)" },
        { term: "Robot", translation: "Robot" },
        { term: "Robotics", translation: "Robotika" },
        { term: "Root", translation: "Akar" },
        { term: "Router", translation: "Router" },
        { term: "Row", translation: "Baris" },
        { term: "RPM (Revolutions per minute)", translation: "RPM (Putaran per menit)" },
        { term: "RSS (Rich Site Summary)", translation: "RSS (Ringkasan Situs Kaya)" },
        { term: "RTF (Rich Text Format)", translation: "RTF (Format Teks Kaya)" },
        { term: "Runtime", translation: "Runtime" },
        { term: "SaaS (Software as a Service)", translation: "SaaS (Perangkat Lunak sebagai Layanan)" },
        { term: "Safari", translation: "Safari" },
        { term: "Safety", translation: "Keamanan" },
        { term: "SAN (Storage Area Network)", translation: "SAN (Jaringan Area Penyimpanan)" },
        { term: "Scalability", translation: "Scalability" },
        { term: "Scanner", translation: "Pemindai" },
        { term: "Scanning", translation: "Pemindaian" },
        { term: "Scareware", translation: "Scareware" },
        { term: "SCSI (Small Computer System Interface)", translation: "SCSI (Antarmuka Sistem Komputer Kecil)" },
        { term: "Script", translation: "Skrip" },
        { term: "Scrum", translation: "Scrum" },
        { term: "SDK (Software Development Kit)", translation: "SDK (Paket Pengembangan Perangkat Lunak)" },
        { term: "Search engine", translation: "Mesin pencari" },
        { term: "Search engine optimization (SEO)", translation: "Optimisasi mesin pencari (SEO)" },
        { term: "Secure", translation: "Aman" },
        { term: "Security", translation: "Keamanan" },
        { term: "Security token", translation: "Token keamanan" },
        { term: "Segment", translation: "Segmen" },
        { term: "Selfie", translation: "Selfie" },
        { term: "Semantic web", translation: "Web semantik" },
        { term: "Semaphore", translation: "Semafor" },
        { term: "Sensor", translation: "Sensor" },
        { term: "SEO (Search Engine Optimization)", translation: "SEO (Optimisasi Mesin Pencari)" },
        { term: "Server", translation: "Server" },
        { term: "Servlet", translation: "Servlet" },
        { term: "Session", translation: "Sesi" },
        { term: "Shareware", translation: "Shareware" },
        { term: "Shell", translation: "Shell" },
        { term: "Shift", translation: "Shift" },
        { term: "Shopping cart", translation: "Troli belanja" },
        { term: "Shortcut", translation: "Jalan pintas" },
        { term: "Sidebar", translation: "Sidebar" },
        { term: "Signal", translation: "Sinyal" },
        { term: "Signature", translation: "Tanda tangan" },
        { term: "SIM card (Subscriber Identity Module card)", translation: "Kartu SIM (Kartu Modul Identitas Pelanggan)" },
        { term: "Simulation", translation: "Simulasi" },
        { term: "Skype", translation: "Skype" },
        { term: "Slack", translation: "Slack" },
        { term: "Slashdot effect", translation: "Efek Slashdot" },
        { term: "Slideshow", translation: "Slideshow" },
        { term: "Smartphone", translation: "Ponsel pintar" },
        { term: "SMTP (Simple Mail Transfer Protocol)", translation: "SMTP (Protokol Transfer Surat Elektronik Sederhana)" },
        { term: "Snapchat", translation: "Snapchat" },
        { term: "Sniffer", translation: "Pengendus" },
        { term: "Social engineering", translation: "Teknik sosial" },
        { term: "Social media", translation: "Media sosial" },
        { term: "Socket", translation: "Socket" },
        { term: "Software", translation: "Perangkat lunak" },
        { term: "Software development", translation: "Pengembangan perangkat lunak" },
        { term: "Software engineer", translation: "Insinyur perangkat lunak" },
        { term: "Software piracy", translation: "Pembajakan perangkat lunak" },
        { term: "Software update", translation: "Pembaruan perangkat lunak" },
        { term: "Solution", translation: "Solusi" },
        { term: "Sound card", translation: "Kartu suara" },
        { term: "Spam", translation: "Spam" },
        { term: "Speaker", translation: "Pengeras suara" },
        { term: "Spooling", translation: "Spooling" },
        { term: "Spreadsheet", translation: "Lembar kerja" },
        { term: "SQL (Structured Query Language)", translation: "SQL (Bahasa Permintaan Terstruktur)" },
        { term: "SQL injection", translation: "Injeksi SQL" },
        { term: "SSL (Secure Sockets Layer)", translation: "SSL (Lapisan Soket Aman)" },
        { term: "Stack", translation: "Tumpukan" },
        { term: "Star topology", translation: "Topologi bintang" },
        { term: "Startup", translation: "Startup" },
        { term: "Storage", translation: "Penyimpanan" },
        { term: "Storage area network (SAN)", translation: "Jaringan area penyimpanan (SAN)" },
        { term: "Streaming", translation: "Streaming" },
        { term: "Structured programming", translation: "Pemrograman terstruktur" },
        { term: "Style sheet", translation: "Lembar gaya" },
        { term: "Subnet", translation: "Subnet" },
        { term: "Subroutine", translation: "Subrutin" },
        { term: "Subscript", translation: "Subskrip" },
        { term: "Subsystem", translation: "Subsistem" },
        { term: "Substitute", translation: "Ganti" },
        { term: "Suffix", translation: "Sufiks" },
        { term: "Supercomputer", translation: "Superkomputer" },
        { term: "Superscript", translation: "Superskrip" },
        { term: "Supply chain management (SCM)", translation: "Manajemen rantai pasokan (SCM)" },
        { term: "Surge protector", translation: "Pelindung lonjakan" },
        { term: "Surveillance", translation: "Survei" },
        { term: "SVG (Scalable Vector Graphics)", translation: "SVG (Grafis Vektor Skalabel)" },
        { term: "Switch", translation: "Switch" },
        { term: "Symbol", translation: "Simbol" },
        { term: "Synchronization", translation: "Sinkronisasi" },
        { term: "Syntax", translation: "Sintaksis" },
        { term: "System", translation: "Sistem" },
        { term: "System administrator", translation: "Administrator sistem" },
        { term: "System analyst", translation: "Analis sistem" },
        { term: "System clock", translation: "Jam sistem" },
        { term: "System software", translation: "Perangkat lunak sistem" },
        { term: "Table", translation: "Tabel" },
        { term: "Tablet", translation: "Tablet" },
        { term: "Tag", translation: "Tag" },
        { term: "TCP/IP (Transmission Control Protocol/Internet Protocol)", translation: "TCP/IP (Protokol Kontrol Transmisi/Protokol Internet)" },
        { term: "Template", translation: "Template" },
        { term: "Terabyte", translation: "Terabyte" },
        { term: "Terminal", translation: "Terminal" },
        { term: "Terminator", translation: "Terminator" },
        { term: "Text", translation: "Teks" },
        { term: "Text editor", translation: "Editor teks" },
        { term: "Text messaging", translation: "Pesan teks" },
        { term: "Texture mapping", translation: "Pemetaan tekstur" },
        { term: "Thermal printer", translation: "Printer termal" },
        { term: "Thread", translation: "Utas" },
        { term: "Thumbnail", translation: "Gambar kecil" },
        { term: "TIFF (Tagged Image File Format)", translation: "TIFF (Format Berkas Gambar Berlabel)" },
        { term: "Time-sharing", translation: "Pemakaian waktu" },
        { term: "Toolbar", translation: "Toolbar" },
        { term: "Topology", translation: "Topologi" },
        { term: "Torrent", translation: "Torrent" },
        { term: "Touchpad", translation: "Touchpad" },
        { term: "Trackball", translation: "Trackball" },
        { term: "Tracker", translation: "Pelacak" },
        { term: "Trademark", translation: "Merek dagang" },
        { term: "Traffic", translation: "Lalu lintas" },
        { term: "Training", translation: "Pelatihan" },
        { term: "Transaction", translation: "Transaksi" },
        { term: "Transmission", translation: "Transmisi" },
        { term: "Transmitter", translation: "Pengirim" },
        { term: "Trojan horse", translation: "Kuda Troya" },
        { term: "Troubleshooting", translation: "Pemecahan masalah" },
        { term: "Tumblr", translation: "Tumblr" },
        { term: "Twitter", translation: "Twitter" },
        { term: "Typeface", translation: "Huruf" },
        { term: "Ubuntu", translation: "Ubuntu" },
        { term: "UDP (User Datagram Protocol)", translation: "UDP (Protokol Datagram Pengguna)" },
        { term: "UI (User Interface)", translation: "UI (Antarmuka Pengguna)" },
        { term: "Ultra HD", translation: "Ultra HD" },
        { term: "UML (Unified Modeling Language)", translation: "UML (Bahasa Pemodelan Terpadu)" },
        { term: "Unicode", translation: "Unicode" },
        { term: "Unix", translation: "Unix" },
        { term: "Upload", translation: "Unggah" },
        { term: "UPS (Uninterruptible Power Supply)", translation: "UPS (Sumber Daya Listrik Tak Terputus)" },
        { term: "URL (Uniform Resource Locator)", translation: "URL (Locator Sumber Daya Seragam)" },
        { term: "USB (Universal Serial Bus)", translation: "USB (Bus Seri Universal)" },
        { term: "User", translation: "Pengguna" },
        { term: "Username", translation: "Nama pengguna" },
        { term: "Utility software", translation: "Perangkat lunak utilitas" },
        { term: "UTF-8 (Unicode Transformation Format 8-bit)", translation: "UTF-8 (Format Transformasi Unicode 8-bit)" },
        { term: "Validation", translation: "Validasi" },
        { term: "VGA (Video Graphics Array)", translation: "VGA (Susunan Grafis Video)" },
        { term: "Virus", translation: "Virus" },
        { term: "Virtual", translation: "Virtual" },
        { term: "Virtual memory", translation: "Memori virtual" },
        { term: "Virtual private network (VPN)", translation: "Jaringan pribadi virtual (VPN)" },
        { term: "Virtual reality (VR)", translation: "Realitas virtual (VR)" },
        { term: "Virus scan", translation: "Pemindaian virus" },
        { term: "Visual Basic", translation: "Visual Basic" },
        { term: "Visualization", translation: "Visualisasi" },
        { term: "VLAN (Virtual Local Area Network)", translation: "VLAN (Jaringan Area Lokal Virtual)" },
        { term: "Vlog (Video Blog)", translation: "Vlog (Blog Video)" },
        { term: "VoIP (Voice over Internet Protocol)", translation: "VoIP (Panggilan suara via Internet)" },
        { term: "Vulnerability", translation: "Kerentanan" },
        { term: "W3C (World Wide Web Consortium)", translation: "W3C (Konsorsium World Wide Web)" },
        { term: "WAN (Wide Area Network)", translation: "WAN (Jaringan Luas)" },
        { term: "WAP (Wireless Application Protocol)", translation: "WAP (Protokol Aplikasi Nirkabel)" },
        { term: "Warez", translation: "Warez" },
        { term: "Warm boot", translation: "Pemanasan boot" },
        { term: "WAV (Waveform Audio File Format)", translation: "WAV (Format Berkas Audio Gelombang)" },
        { term: "Web 2.0", translation: "Web 2.0" },
        { term: "Web browser", translation: "Browser web" },
        { term: "Web designer", translation: "Perancang web" },
        { term: "Web development", translation: "Pengembangan web" },
        { term: "Web hosting", translation: "Hosting web" },
        { term: "Web page", translation: "Halaman web" },
        { term: "Web server", translation: "Server web" },
        { term: "Webcam", translation: "Webcam" },
        { term: "Website", translation: "Situs web" },
        { term: "Wi-Fi", translation: "Wi-Fi" },
        { term: "Wiki", translation: "Wiki" },
        { term: "Windows", translation: "Windows" },
        { term: "Windows Explorer", translation: "Windows Explorer" },
        { term: "Wired", translation: "Kabel" },
        { term: "Wireless", translation: "Nirkabel" },
        { term: "Word processor", translation: "Pemroses kata" },
        { term: "Workflow", translation: "Alur kerja" },
        { term: "Workstation", translation: "Workstation" },
        { term: "World Wide Web", translation: "World Wide Web" },
        { term: "Worm", translation: "Cacing" },
        { term: "WPA (Wi-Fi Protected Access)", translation: "WPA (Akses Terlindungi Wi-Fi)" },
        { term: "WYSIWYG (What You See Is What You Get)", translation: "WYSIWYG (Apa yang Anda Lihat Adalah Apa yang Anda Dapatkan)" },
        { term: "XML (eXtensible Markup Language)", translation: "XML (Bahasa Pemrosesan Ekstensibel)" },
        { term: "Yahoo!", translation: "Yahoo!" },
        { term: "YouTube", translation: "YouTube" },
        { term: "Zettabyte", translation: "Zettabyte" },
        { term: "ZIP", translation: "ZIP" },
        { term: "Zoom", translation: "Zoom" },
        { term: "Zombie", translation: "Zombie" }
];

// Function to render the dictionary
function renderDictionary(terms) {
    var container = document.getElementById('dictionaryContainer');
    container.innerHTML = ''; // Clear previous content

    terms.forEach(function(term) {
        var termDiv = document.createElement('div');
        termDiv.classList.add('column');
        termDiv.innerHTML = `
            <table class="term-table">
                <tr>
                    <th class="blue">Term</th>
                    <th class="orange">Translation</th>
                </tr>
                <tr>
                    <td>${term.term}</td>
                    <td>${term.translation}</td>
                </tr>
            </table>
        `;
        container.appendChild(termDiv);
    });
}

// Initial rendering of the dictionary
renderDictionary(dictionary);

// Function to search for a term
function search() {
    var searchTerm = document.getElementById('searchTerm').value.toLowerCase();
    var searchResults = dictionary.filter(function(term) {
        return term.term.toLowerCase().includes(searchTerm);
    });
    renderDictionary(searchResults);
}
